// GENERATED by scripts/load — do not edit. Proves src/protocol/discovery.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/protocol/discovery.ts", async () => {
  const mod = await import("../../src/protocol/discovery.js");
  expect(mod).toBeDefined();
});
